#!/usr/bin/env bash
set -e
sh install

pushd $(dirname $0)

pushd tests/01
../../bin/wolfpack --verbose
cmake --preset example
cmake --build build --parallel
popd

pushd tests/02
../../bin/wolfpack --verbose
cmake --preset example
cmake --build build --parallel
popd

popd